# Use a imagem base Python
FROM python:3.9

# Defina o diretório de trabalho
WORKDIR /app

# Copie o requirements.txt e instale as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie o código da API para o container
COPY API/ .

# Exponha a porta usada pela API
EXPOSE 5000

# Comando para rodar a API
CMD ["python", "main.py"]
