version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    container_name: c115_api
    networks:
      - c115_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    container_name: c115_frontend
    networks:
      - c115_network
    extra_hosts:
      - "localhost:172.18.0.3"

networks:
  c115_network:
    driver: bridge
